export type SiteNovel = {
  id: string;
  slug: string;
  title: string;
  author: string;
  genre: string;
  rating: number;
  chapters: number;
  views: string;
  status: "ONGOING" | "COMPLETED" | "HIATUS";
  type: "chinese" | "korean" | "japanese" | "english";
  latestChapter: string;
  coverUrl: string;
  bannerUrl: string;
  tags: string[];
  description: string;
  updatedAt: string;
  addedAt: number;
};

const cloudinaryDemo = "https://res.cloudinary.com/demo/image/upload";

export const GENRES = [
  "All", "Action", "Fantasy", "Romance", "Cultivation", "Regression",
  "System", "Isekai", "Horror", "Mystery", "Sci-Fi", "Dark Fantasy",
  "Xianxia", "Wuxia", "Drama", "Comedy", "Psychological", "Martial Arts",
  "Supernatural", "Tragedy", "Slice of Life", "Seinen", "Shounen",
  "Historical", "School Life", "Mecha", "Game",
];

export const GENRE_META: Record<string, { desc: string }> = {
  Action: { desc: "A work typically depicting fighting, violence, chaos, and fast paced motion." },
  Adventure: { desc: "Exploring new places, environments or situations." },
  Fantasy: { desc: "Anything that involves magic, dream world, and fairy tales." },
  Romance: { desc: "A story focusing on romantic relationships." },
  Cultivation: { desc: "Characters train and refine to achieve higher levels of power." },
  Regression: { desc: "A protagonist travels back in time to change their fate." },
  System: { desc: "Novels related to game-like elements, RPG stats, or hidden systems." },
  Isekai: { desc: "A protagonist is transported to another world." },
  Horror: { desc: "Novels focused on scaring through fear and supernatural elements." },
  Mystery: { desc: "An unexplained event occurs and the protagonist investigates." },
  "Sci-Fi": { desc: "Science fiction involving technology and futuristic concepts." },
  "Dark Fantasy": { desc: "Fantasy with darker, frightening themes and morally ambiguous characters." },
  Xianxia: { desc: "Martial art stories about cultivating to immortality, influenced by Chinese folklore." },
  Wuxia: { desc: "Martial arts stories in ancient China settings." },
  Drama: { desc: "Works meant to evoke emotional responses through conflict and character development." },
  Comedy: { desc: "Light and humorous works with happy resolutions." },
  Psychological: { desc: "Deals with philosophy of mind and complex psychology." },
  "Martial Arts": { desc: "Focus on arts of combat or self-defense." },
  Supernatural: { desc: "Unexplained powers or events defying physics." },
  Tragedy: { desc: "Events resulting in great loss and misfortune." },
  "Slice of Life": { desc: "Naturalistic focus on characters and everyday lives." },
  Seinen: { desc: "Targeting young adult males around 18-25." },
  Shounen: { desc: "Written for younger male audiences, usually involving fighting." },
  Historical: { desc: "Setting in the past, following historical tales." },
  "School Life": { desc: "Story set in a school environment." },
  Mecha: { desc: "Involving large robotic machines." },
  Game: { desc: "Novels related to game elements or game-like systems." },
};

export const featuredNovels: SiteNovel[] = [
  {
    id: "1",
    slug: "shadow-monarchs-ascension",
    title: "Shadow Monarch's Ascension",
    author: "Lee Sung-woo",
    genre: "Action",
    rating: 4.9,
    chapters: 542,
    views: "12.4M",
    status: "ONGOING",
    type: "korean",
    latestChapter: "Ch. 542: The Final Gate Opens",
    coverUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&h=640&fit=crop&auto=format",
    tags: ["Action", "Fantasy", "Op MC", "System", "Manhwa"],
    description: "Sung Jin-Woo, the weakest hunter of all mankind, finds himself trapped in a deadly double dungeon. Facing certain death, he discovers a mysterious quest — one that will transform him into the most powerful being the world has ever seen.",
    updatedAt: "2 hours ago",
    addedAt: 1700000001,
  },
  {
    id: "2",
    slug: "celestial-emperors-legacy",
    title: "Celestial Emperor's Legacy",
    author: "Wang Xiao",
    genre: "Fantasy",
    rating: 4.7,
    chapters: 328,
    views: "8.1M",
    status: "ONGOING",
    type: "chinese",
    latestChapter: "Ch. 328: Ascension to the Heavens",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&h=640&fit=crop&auto=format",
    tags: ["Xianxia", "Cultivation", "Rebirth", "Emperor"],
    description: "A fallen emperor is reborn with memories of his past life and vows to reclaim his throne. Armed with forbidden cultivation techniques, he treads the path between heaven and mortal.",
    updatedAt: "5 hours ago",
    addedAt: 1700000005,
  },
  {
    id: "3",
    slug: "infinite-regression-chronicles",
    title: "Infinite Regression Chronicles",
    author: "Park Ji-hun",
    genre: "Regression",
    rating: 4.8,
    chapters: 412,
    views: "9.7M",
    status: "ONGOING",
    type: "korean",
    latestChapter: "Ch. 412: The Last Loop",
    coverUrl: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1600&h=640&fit=crop&auto=format",
    tags: ["Regression", "Time Loop", "Apocalypse", "Op MC"],
    description: "Every time he dies, the world resets. After a thousand loops watching humanity fall, the Last Regressor decides this time will be different.",
    updatedAt: "3 hours ago",
    addedAt: 1700000003,
  },
];

export const catalogNovels: SiteNovel[] = [
  ...featuredNovels,
  {
    id: "4",
    slug: "mystic-cultivation-chronicles",
    title: "Mystic Cultivation Chronicles",
    author: "Chen Wei",
    genre: "Cultivation",
    rating: 4.9,
    chapters: 612,
    views: "15.2M",
    status: "ONGOING",
    type: "chinese",
    latestChapter: "Ch. 612: The Dao of Immortality",
    coverUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&h=640&fit=crop&auto=format",
    tags: ["Cultivation", "Wuxia", "Immortality", "Martial Arts", "Adventure"],
    description: "An orphan with blocked meridians stumbles upon an ancient jade slip containing the lost techniques of a supreme cultivator. Against all odds, he embarks on a journey to reach the peak of immortality.",
    updatedAt: "1 day ago",
    addedAt: 1700000010,
  },
  {
    id: "5",
    slug: "the-void-sorcerer",
    title: "The Void Sorcerer",
    author: "Kang Min-jun",
    genre: "Dark Fantasy",
    rating: 4.6,
    chapters: 287,
    views: "5.3M",
    status: "ONGOING",
    type: "korean",
    latestChapter: "Ch. 287: Into the Abyss",
    coverUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=1600&h=640&fit=crop&auto=format",
    tags: ["Dark Fantasy", "Magic", "Antihero", "Political"],
    description: "Condemned for a crime he didn't commit, a court mage discovers that void magic banned by the kingdom is the only power capable of stopping the darkness threatening the continent.",
    updatedAt: "6 hours ago",
    addedAt: 1700000006,
  },
  {
    id: "6",
    slug: "void-emperors-decree",
    title: "Void Emperor's Decree",
    author: "Park Ji-hun",
    genre: "Action",
    rating: 4.5,
    chapters: 214,
    views: "4.1M",
    status: "ONGOING",
    type: "korean",
    latestChapter: "Ch. 214: Battle at the Edge of Reality",
    coverUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&h=640&fit=crop&auto=format",
    tags: ["Action", "System", "Dungeon", "Revenge"],
    description: "Betrayed by the empire he served, a legendary general awakens in a world transformed by void rifts. Armed with a forbidden system, he carves a path of reckoning.",
    updatedAt: "8 hours ago",
    addedAt: 1700000008,
  },
  {
    id: "7",
    slug: "eternal-sakura-reborn",
    title: "Eternal Sakura Reborn",
    author: "Aiko Tanaka",
    genre: "Romance",
    rating: 4.8,
    chapters: 195,
    views: "6.7M",
    status: "COMPLETED",
    type: "japanese",
    latestChapter: "Ch. 195: Forever Begins",
    coverUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1600&h=640&fit=crop&auto=format",
    tags: ["Romance", "Isekai", "Reincarnation", "Shoujo"],
    description: "A modern woman wakes up as the villainess destined to die in her favourite novel. Determined to rewrite her fate, she navigates court politics — and an unexpected love story.",
    updatedAt: "2 days ago",
    addedAt: 1700000020,
  },
  {
    id: "8",
    slug: "iron-blood-mercenary",
    title: "Iron Blood Mercenary",
    author: "Zhao Fang",
    genre: "Action",
    rating: 4.4,
    chapters: 389,
    views: "3.8M",
    status: "COMPLETED",
    type: "chinese",
    latestChapter: "Ch. 389: Last Contract",
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&h=640&fit=crop&auto=format",
    tags: ["Action", "Wuxia", "Adventure", "Brotherhood"],
    description: "A retired war veteran takes one final mercenary job to save his village — only to be dragged into a conspiracy that spans the entire continent.",
    updatedAt: "3 days ago",
    addedAt: 1700000030,
  },
  {
    id: "9",
    slug: "the-dragon-empress",
    title: "The Dragon Empress",
    author: "Mei Ling",
    genre: "Fantasy",
    rating: 4.7,
    chapters: 445,
    views: "7.9M",
    status: "COMPLETED",
    type: "chinese",
    latestChapter: "Ch. 445: The Eternal Flame",
    coverUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1600&h=640&fit=crop&auto=format",
    tags: ["Fantasy", "Female Lead", "Dragons", "Political"],
    description: "Born with dragon blood in a world that fears her kind, a young empress must unite warring kingdoms before an ancient evil devours the realm.",
    updatedAt: "1 week ago",
    addedAt: 1700000040,
  },
  {
    id: "10",
    slug: "system-override",
    title: "System Override",
    author: "Kim Dae-jung",
    genre: "Sci-Fi",
    rating: 4.6,
    chapters: 278,
    views: "4.5M",
    status: "ONGOING",
    type: "korean",
    latestChapter: "Ch. 278: Hack the World",
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&h=640&fit=crop&auto=format",
    tags: ["Sci-Fi", "System", "Cyberpunk", "Hacker"],
    description: "When a rogue AI grants him admin-level access to the world's hidden RPG system, a lowly data analyst becomes humanity's last line of defence against digital apocalypse.",
    updatedAt: "4 hours ago",
    addedAt: 1700000004,
  },
  {
    id: "11",
    slug: "moonlit-villainess",
    title: "Moonlit Villainess",
    author: "Seo Yuna",
    genre: "Romance",
    rating: 4.5,
    chapters: 163,
    views: "3.2M",
    status: "ONGOING",
    type: "korean",
    latestChapter: "Ch. 163: The Duke's Offer",
    coverUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1600&h=640&fit=crop&auto=format",
    tags: ["Romance", "Villainess", "Isekai", "Slow Burn"],
    description: "Transmigrated into the body of a noble villainess, she only wants to live quietly — but fate, and a certain cold-hearted duke, have other plans.",
    updatedAt: "12 hours ago",
    addedAt: 1700000012,
  },
  {
    id: "12",
    slug: "abyss-walker",
    title: "Abyss Walker",
    author: "Ryu Hajime",
    genre: "Horror",
    rating: 4.3,
    chapters: 201,
    views: "2.6M",
    status: "HIATUS",
    type: "japanese",
    latestChapter: "Ch. 201: What Lurks Below",
    coverUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=360&h=540&fit=crop&auto=format",
    bannerUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=1600&h=640&fit=crop&auto=format",
    tags: ["Horror", "Mystery", "Psychological"],
    description: "A detective who can see the dead is assigned to investigate disappearances near an ancient temple — where something far older than ghosts waits in the dark.",
    updatedAt: "3 weeks ago",
    addedAt: 1700000050,
  },
];
